### ISSUE TITLE
"One line installer" does not work on Ubuntu 20.04 and 22.04

### ISSUE THREAD

**Issue by tannerdsilva** [haveno-dex/haveno-pricenode#2]
Hello.

Recently tried launching one of these price nodes for CakeWallet, and I came across some issues.

On Ubuntu 22.04: there are interactive prompts that ask "which systemd services should be restarted" when new packages are installed. These prompts are not handled properly in the script, and prevent the script from finishing.

After discovering this, I tried the script on Ubuntu 20.04 (which does not have these prompts). The script went much further, however, still fell short of completing.

Without posting the entire output, the script failed at this point:

```
BUILD SUCCESSFUL in 4m 13s
38 actionable tasks: 38 executed
[*] Installing haveno-pricenode systemd service
install: cannot stat '/haveno/haveno-pricenode/scripts/haveno-pricenode.service': No such file or directory
```

These failures prevent the "one line installer" from working as promised.

**Comment by woodser** [comment]
@tannerdsilva https://github.com/haveno-dex/haveno-pricenode/pull/3 should fix the install script. Please try again with the latest commit to main and let me know if there is any problem. Thanks.

**Comment by woodser** [comment]
@tannerdsilva 

We would really appreciate deployment of the new server as soon as possible, since we have a list of dependencies awaiting its availability, including [updating the client code](https://github.com/haveno-dex/haveno/pull/503) which depends on it, and then [docker support and Continuous Integration (CI) tests](https://github.com/haveno-dex/haveno-ts/pull/156/commits).

**Comment by tannerdsilva** [comment]
Thanks for the update. Tried the one-liner in the README again this morning (in a rush) and realized some hours later that your HTTP cache does not actually reflect the latest commit on master. This should have been obvious to me.

Trying again with an actual clone of the repo - will update you in the morning on the results. Script running as I write...

**Comment by tannerdsilva** [comment]
Same issue still. From commit hash `e9994ee03a1e762a94afba8eceee5cac57fca479` on a fresh Ubuntu 20.04:

```
BUILD SUCCESSFUL in 4m 26s
38 actionable tasks: 38 executed
[*] Installing haveno-pricenode systemd service
install: cannot stat '/haveno/../haveno-pricenode/scripts/haveno-pricenode.service': No such file or directory
```

**Comment by woodser** [comment]
Do you have the haveno-pricenode project in the same parent directory as the haveno project?

**Comment by tannerdsilva** [comment]
I'm just starting on a fresh system (nothing installed), cloning `haveno-pricenode` into the root home folder, and running the script in place.

`/root/haveno-pricenode`

**Comment by woodser** [comment]
Ok. Please try cloning the haveno project to the same directory. That may resolve the error.

**Comment by tannerdsilva** [comment]
Same result.

**Comment by woodser** [comment]
You cloned the repository using the recursive option?

`git clone --recursive https://github.com/haveno-dex/haveno-pricenode.git`

**Comment by tannerdsilva** [comment]
Yes, same result.

```
BUILD SUCCESSFUL in 4m 15s
38 actionable tasks: 38 executed
[*] Installing haveno-pricenode systemd service
install: cannot stat '/haveno/../haveno-pricenode/scripts/haveno-pricenode.service': No such file or directory
```

**Comment by woodser** [comment]
What did you need to do to clear the HTTP cache? I need to do the same.

**Comment by woodser** [comment]
I found and fixed the issue. A couple scripts just needed to be renamed.

I force pushed the fix to main since it took some experimentation which I want to remove from the commit history, so please `git reset --hard d89effc80bf24f95d7e9673324ab85a5ab9205e1`, the latest commit on main.

Please run on Ubuntu 22.04 which is preferred over 20.04 for future updates. Might just need to run the one-liner with sudo to bypass any prompts:

`sudo curl -s https://raw.githubusercontent.com/haveno-dex/haveno-pricenode/main/scripts/install_pricenode_debian.sh | sudo bash`

Thanks, should be good to deploy now.

**Comment by woodser** [comment]
@tannerdsilva Any updates?
